version: '3.3'

services:
   db:
     container_name: ithemal_mysql
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ithemal
       MYSQL_DATABASE: ithemal

   ithemal:
     container_name: ithemal
     depends_on:
       - db
     volumes:
       - type: bind
         source: ..
         target: /home/ithemal/ithemal
     image: ithemal:latest
     tty: true
     environment:
       MYSQL_HOST: db
       MYSQL_TCP_PORT: 3306
       HISTFILE: /home/ithemal/ithemal/docker/.docker_bash_history
       ITHEMAL_HOME: /home/ithemal/ithemal
     ports:
       - "8888:8888"

volumes:
    db_data:
